name: Documentation

on:
  push:
    branches:
      - main
      - render-images-for-docs

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build documentation
        run: >
          swift package --allow-writing-to-directory docs \
            generate-documentation \
            --target Flow \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path /Flow \
            --output-path docs

      - name: Render examples
        run: |
          swift run Renderer --width 350 --fixed-height > Resources/hflow.png
          swift run Renderer --width 350 --layout-direction right-to-left --fixed-height > Resources/hflow-rtl.png
          swift run Renderer --height 350 --axis vertical --fixed-width > Resources/vflow.png
          swift run Renderer --width 350 --item-spacing 2 --line-spacing 20 --fixed-width --fixed-height > Resources/hflow-spacing.png
          swift run Renderer --width 350 --alignment top --fixed-width > Resources/hflow-top.png
      
      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs
          git-config-name: László Teveli
          git-config-email: tevelee@gmail.com
